plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
url: https://alxfed.github.io
baseurl: /webmachine

title: webmachine
description: A machine is a thing. Things can not think. ...but some of them can thingk!

exclude:
  - README.md
  - LICENSE

machina:
  name: Thingking-Machine,
  instructions_file: thingking.txt
  token: fireworks.txt
  apiUrl: https://api.fireworks.ai/inference/v1/chat/completions
  default_llm: accounts/fireworks/models/llama-v3p1-8b-instruct

github_settings:
  owner: thingking-machine
  repo: thingking_machine
  file_name: machina.yaml
  branch: main
  token_file: github.txt

